### ISSUE TITLE
[BUG]: Does not compile on OptiX 9.0.0

### ISSUE THREAD

**Issue by julcst** [NVIDIA/cuCollections#724]
### Is this a duplicate?

- [x] I confirmed there appear to be no duplicate issues for this bug (https://github.com/NVIDIA/cuCollections/issues)

### Type of Bug

Compile-time Error

### Describe the bug

Does not compile on OptiX 9.0.0 with error:

```
[build] /home/julcs/Documents/binrc/build/_deps/cccl-src/lib/cmake/libcudacxx/../../../libcudacxx/include/cuda/std/__utility/convert_to_integral.h(68): error: "__int128_t (__int128_t)" (aka "__int128 (__int128)") contains a 128-bit integer, which is not supported in device code
[build]   __attribute__((__visibility__("hidden"))) inline __attribute__((host)) __attribute__((device)) constexpr __int128_t __convert_to_integral(__int128_t __val)
[build]                                                                                                                       ^
[build] 
[build] /home/julcs/Documents/binrc/build/_deps/cccl-src/lib/cmake/libcudacxx/../../../libcudacxx/include/cuda/std/__utility/convert_to_integral.h(73): error: "__uint128_t (__uint128_t)" (aka "unsigned __int128 (unsigned __int128)") contains a 128-bit integer, which is not supported in device code
[build]   __attribute__((__visibility__("hidden"))) inline __attribute__((host)) __attribute__((device)) constexpr __uint128_t __convert_to_integral(__uint128_t __val)
[build]
...
```

### How to Reproduce

```cpp
#include  <cuco/static_multimap.cuh>
```

inside an OptiX file

According to https://github.com/NVIDIA/cccl/issues/1227 this should be fixed with:

```cpp
#define _LIBCUDACXX_HAS_NO_INT128
#include  <cuco/static_multimap.cuh>
```

but then I get:

```
[build] /home/julcs/Documents/binrc/build/_deps/cccl-src/lib/cmake/cub/../../../cub/cub/util_type.cuh(999): error: "cub::NumericTraits<__uint128_t>::UnsignedBits (cub::NumericTraits<__uint128_t>::UnsignedBits)" (aka "unsigned __int128 (unsigned __int128)") contains a 128-bit integer, which is not supported in device code
[build]     static __attribute__((host)) __attribute__((device)) __inline__ __attribute__((__always_inline__)) UnsignedBits TwiddleIn(UnsignedBits key)
[build]                                                                                                                     ^
[build] 
[build] /home/julcs/Documents/binrc/build/_deps/cccl-src/lib/cmake/cub/../../../cub/cub/util_type.cuh(1004): error: "cub::NumericTraits<__uint128_t>::UnsignedBits (cub::NumericTraits<__uint128_t>::UnsignedBits)" (aka "unsigned __int128 (unsigned __int128)") contains a 128-bit integer, which is not supported in device code
[build]     static __attribute__((host)) __attribute__((device)) __inline__ __attribute__((__always_inline__)) UnsignedBits TwiddleOut(UnsignedBits key)
```
### Expected behavior

Should compile

### Operating System

Fedora 42

### nvidia-smi output

+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 570.153.02             Driver Version: 570.153.02     CUDA Version: 12.8     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA GeForce RTX 3060 Ti     Off |   00000000:0A:00.0  On |                  N/A |
| 30%   52C    P5             29W /  200W |     337MiB /   8192MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

### NVCC version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2025 NVIDIA Corporation
Built on Fri_Feb_21_20:23:50_PST_2025
Cuda compilation tools, release 12.8, V12.8.93
Build cuda_12.8.r12.8/compiler.35583870_0

**Comment by julcst** [comment]
Ok so defining

```cpp
#define _CCCL_DISABLE_INT128
```

Fixes this error

**Comment by miscco** [comment]
@julcst could I get some additional information on what exact CCCL version and host compiler is used here
