### PR TITLE
Add Arrow bloom filter policy

### PR DESCRIPTION
**Pull request by mhaseeb123**
This PR adds a new Bloom Filter policy implementing the Arrow BF algorithm. This PR is a part of https://github.com/rapidsai/cudf/issues/17164. A follow-up PR will add tests for bitwise validation of bloom filter using arrow policy.

### CODE REVIEW

File: include/cuco/detail/bloom_filter/arrow_bf_policy_impl.cuh [hunk 1]
```diff
@@ -0,0 +1,93 @@
...
+ public:
+  using hasher    = cuco::xxhash_64<T>;  ///< xxhash_64 hasher for Arrow bloom filter policy
+  using word_type = std::uint32_t;       ///< uint32_t for Arrow bloom filter policy
+  using hash_argument_type = typename hasher::argument_type;
+  using hash_result_type   = decltype(std::declval<hasher>()(std::declval<hash_argument_type>()));
+
+  static constexpr uint32_t bits_set_per_block = 8;  ///< hardcoded  bits set per Arrow bf block
+  static constexpr uint32_t words_per_block    = 8;  ///< hardcoded words per Arrow bf block
+
+  __host__ __device__ explicit constexpr arrow_bf_policy_impl(std::uint32_t num_blocks, hasher hash)
```
Comment (mhaseeb123) [inline include/cuco/detail/bloom_filter/arrow_bf_policy_impl.cuh]: We are only using the `num_blocks` to validate the filter size to be in range: [32B, 128MB] (Arrow hardcoding). The constructor doesn't need `pattern_bits` as those are fixed in `SALT` array.

File: examples/bloom_filter/arrow_bf_host_bulk_example.cu [hunk 2]
```diff
@@ -0,0 +1,79 @@
+/*
+ * Copyright (c) 2024, NVIDIA CORPORATION.
```
Comment (mhaseeb123) [inline examples/bloom_filter/arrow_bf_host_bulk_example.cu:2]: This file is the exact replica of the `bloom_filter_host_bulk_example.cu` except it uses the `arrow_bf_policy`. Was thinking of removing this and incorporating both of these policies in the same example by throwing contents in a function templated over policy.

File: examples/bloom_filter/host_bulk_example.cu [hunk 3]
```diff
@@ -25,44 +25,68 @@
...
+  // Generate 10'000 keys and insert the first 5'000 into the filter containing of 200 sub-filters.
+  int constexpr num_keys    = 10'000;
+  int constexpr num_tp      = num_keys * 0.5;
+  int constexpr num_tn      = num_keys - num_tp;
+  int constexpr sub_filters = 200;
 
-  thrust::device_vector<int> keys(num_keys);
-  thrust::sequence(keys.begin(), keys.end(), 1);
+  // Lambda function to bulk insert to the provided bloom filter and evaluate FPR.
+  auto bulk_insert_and_evaluate_bloom_filter = [&](auto& filter) {
```
Comment (mhaseeb123) [inline examples/bloom_filter/host_bulk_example.cu]: Templated lambdas are available in C++20 and higher. Can we add the `-std=c++20` flag to this example to avoid compilation errors or should I just use a normal templated function/functor for this.

P.S. It compiles fine on my machine (with gcc13/cuda12.5 devcontainer from cuco repo) but on the updated godbolt link generated by `pre-commit ci` it will likely not work as it has `-std=c++17` flag.

Comment (PointKernel) [reply examples/bloom_filter/host_bulk_example.cu]: Let's use templated functor instead

File: tests/bloom_filter/unique_sequence_test.cu [hunk 4]
```diff
@@ -84,13 +84,14 @@ void test_unique_sequence(Filter& filter, size_type num_keys)
...
 }
 
-TEMPLATE_TEST_CASE_SIG("Unique sequence",
-                       "",
-                       ((class Key, class Policy), Key, Policy),
-                       (int32_t, cuco::bloom_filter_policy<cuco::xxhash_64<int32_t>, uint32_t, 1>),
-                       (int32_t, cuco::bloom_filter_policy<cuco::xxhash_64<int32_t>, uint32_t, 8>),
-                       (int32_t, cuco::bloom_filter_policy<cuco::xxhash_64<int32_t>, uint64_t, 1>),
-                       (int32_t, cuco::bloom_filter_policy<cuco::xxhash_64<int32_t>, uint64_t, 8>))
+TEMPLATE_TEST_CASE_SIG(
```
Comment (mhaseeb123) [inline tests/bloom_filter/unique_sequence_test.cu:87]: Auto formatted by `pre-commit` hook.

File: include/cuco/detail/bloom_filter/arrow_filter_policy.cuh [hunk 5]
```diff
@@ -0,0 +1,137 @@
...
+   * @param hash Hash value of the key
+   * @param word_index Target word/segment within the filter block
+   *
+   * @return The bit pattern for the word/segment in the filter block
+   */
+  __device__ constexpr word_type word_pattern(hash_result_type hash, std::uint32_t word_index) const
+  {
+    // Arrow's block-based bloom filter algorithm needs these eight odd SALT values to calculate
+    // eight indexes of bit to set, one bit in each 32-bit (uint32_t) word.
+    constexpr std::uint32_t SALT[bits_set_per_block] = {0x47b6137bU,
```
Comment (mhaseeb123) [inline include/cuco/detail/bloom_filter/arrow_filter_policy.cuh]: Implemented logic from: https://github.com/apache/arrow/blob/main/cpp/src/parquet/bloom_filter.cc#L219

File: tests/bloom_filter/unique_sequence_test.cu [hunk 6]
```diff
@@ -57,7 +57,7 @@ void test_unique_sequence(Filter& filter, size_type num_keys)
     REQUIRE(cuco::test::all_of(contained.begin(), contained.end(), thrust::identity{}));
   }
 
-  SECTION("After clearing the flter no keys should be contained.")
+  SECTION("After clearing the filter no keys should be contained.")
```
Comment (mhaseeb123) [inline tests/bloom_filter/unique_sequence_test.cu:60]: Fixed minor typo

File: benchmarks/bloom_filter/contains_bench.cu
Comment (PointKernel) [inline benchmarks/bloom_filter/contains_bench.cu:1]: @mhaseeb123 could you please share the benchmark results between the default policy and the arror policy in the PR for reference?

File: examples/bloom_filter/host_bulk_example.cu
Comment (PointKernel) [inline examples/bloom_filter/host_bulk_example.cu:1]: Writing examples is a bit different from the core code; here, the priority is to keep them concise and easy to understand, so avoiding code duplication isn’t the priority. I think it would be more intuitive to create a separate example file specifically to demonstrate the use of the Arrow filter. cc @sleeepyjack

File: include/cuco/bloom_filter.cuh [hunk 7]
```diff
@@ -55,13 +55,13 @@ namespace cuco {
  * @tparam Extent Size type that is used to determine the number of blocks in the filter
  * @tparam Scope The scope in which operations will be performed by individual threads
  * @tparam Policy Type that defines how to generate and store key fingerprints (see
- * `cuco/bloom_filter_policy.cuh`)
+ * `cuco/default_filter_policy.cuh`)
```
Comment (PointKernel) [inline include/cuco/bloom_filter.cuh]:
```suggestion
 * `cuco/bloom_filter_policies.cuh`)
```

File: include/cuco/bloom_filter.cuh [hunk 8]
```diff
@@ -109,7 +109,7 @@ class bloom_filter {
    *
    * @param num_blocks Number of sub-filters or blocks
    * @param scope The scope in which operations will be performed
-   * @param policy Fingerprint generation policy (see `cuco/bloom_filter_policy.cuh`)
+   * @param policy Fingerprint generation policy (see `cuco/default_filter_policy.cuh`)
```
Comment (PointKernel) [inline include/cuco/bloom_filter.cuh]:
```suggestion
   * @param policy Fingerprint generation policy (see `cuco/bloom_filter_policies.cuh`)
```

File: include/cuco/bloom_filter_ref.cuh [hunk 9]
```diff
@@ -60,7 +60,7 @@ class bloom_filter_ref {
    * @param data Pointer to the storage span of the filter
    * @param num_blocks Number of sub-filters or blocks
    * @param scope The scope in which operations will be performed
-   * @param policy Fingerprint generation policy (see `cuco/bloom_filter_policy.cuh`)
+   * @param policy Fingerprint generation policy (see `cuco/default_filter_policy.cuh`)
```
Comment (PointKernel) [inline include/cuco/bloom_filter_ref.cuh]:
```suggestion
   * @param policy Fingerprint generation policy (see `cuco/bloom_filter_policies.cuh`)
```

File: include/cuco/detail/bloom_filter/arrow_filter_policy.cuh (hunk 5 above)
Comment (PointKernel) [reply include/cuco/detail/bloom_filter/arrow_filter_policy.cuh]: > Implemented logic from: https://github.com/apache/arrow/blob/main/cpp/src/parquet/bloom_filter.cc#L219

nit: use `cuda::std::array` instead. Also, can you please add the reference link in the comment?

File: include/cuco/detail/bloom_filter/arrow_filter_policy.cuh [hunk 10]
```diff
@@ -0,0 +1,135 @@
...
+#pragma once
+
+#include <cuco/detail/error.hpp>
+#include <cuco/hash_functions.cuh>
+
+#include <cuda/std/__algorithm_>
+#include <cuda/std/bit>
+#include <cuda/std/limits>
+#include <cuda/std/tuple>
+#include <cuda/std/type_traits>
```
Comment (PointKernel) [inline include/cuco/detail/bloom_filter/arrow_filter_policy.cuh]:
```suggestion
#include <cuco/hash_functions.cuh>

#include <cuda/std/bit>
#include <cuda/std/functional>
#include <cuda/std/limits>
```

**Review by PointKernel — COMMENTED** [review]
Thank you @mhaseeb123. Only some small questions/nits.

Can you please fix the doxygen check failures as well?

**Comment by mhaseeb123** [comment]
## Benchmark Results (Add Unique Size)

## Hardware

```
GPU: NVIDIA RTX 5880 Ada Generation
SM Version: 890 (PTX Version: 860)
Number of SMs: 110
SM Default Clock Rate: 18446744071874 MHz
Global Memory: 23879 MiB Free / 48632 MiB Total
Global Memory Bus Peak: 960 GB/sec (384-bit DDR @10001MHz)
Max Shared Memory: 100 KiB/SM, 48 KiB/Block
L2 Cache Size: 98304 KiB
Maximum Active Blocks: 24/SM
Maximum Active Threads: 1536/SM, 1024/Block
Available Registers: 65536/SM, 65536/Block
ECC Enabled: No
```

## bloom_filter_add_unique_size (default policy)
```
| Key |   Hash    | Word | WordsPerBlock | Distribution | NumInputs | FilterSizeMB | FalsePositiveRate | HBWPeak | LoadEff | StoreEff | L1HitRate | L2HitRate | Samples | Samples |  CPU Time  | Noise |  GPU Time  | Noise | Elem/s  | Samples | Batch GPU  |
|-----|-----------|------|---------------|--------------|-----------|--------------|-------------------|---------|---------|----------|-----------|-----------|---------|---------|------------|-------|------------|-------|---------|---------|------------|
| I64 | xxhash_64 |  U32 |             8 |       UNIQUE | 400000000 |            1 |                 1 |  19.08% | 100.00% |    0.00% |     0.00% |    81.63% |      2x |     15x |  34.367 ms | 8.54% |  34.361 ms | 8.54% | 11.641G |     16x |  37.471 ms |
| I64 | xxhash_64 |  U32 |             8 |       UNIQUE | 400000000 |            2 |                 1 |  19.14% | 100.00% |    0.00% |     0.00% |    81.64% |      2x |     15x |  34.602 ms | 7.68% |  34.597 ms | 7.68% | 11.562G |     16x |  37.817 ms |
| I64 | xxhash_64 |  U32 |             8 |       UNIQUE | 400000000 |            4 |                 1 |  19.08% | 100.00% |    0.00% |     0.00% |    81.62% |      2x |     15x |  35.717 ms | 2.26% |  35.711 ms | 2.26% | 11.201G |     16x |  37.917 ms |
| I64 | xxhash_64 |  U32 |             8 |       UNIQUE | 400000000 |            8 |                 1 |  18.87% | 100.00% |    0.00% |     0.00% |    81.61% |      2x |     14x |  35.881 ms | 1.55% |  35.876 ms | 1.55% | 11.150G |     15x |  38.226 ms |
| I64 | xxhash_64 |  U32 |             8 |       UNIQUE | 400000000 |           16 |                 1 |  18.83% | 100.00% |    0.00% |     0.00% |    81.56% |      2x |     14x |  36.170 ms | 1.00% |  36.165 ms | 1.00% | 11.060G |     15x |  38.272 ms |
| I64 | xxhash_64 |  U32 |             8 |       UNIQUE | 400000000 |           32 |           0.99997 |  19.14% | 100.00% |    0.00% |     0.00% |    81.46% |      2x |     14x |  36.145 ms | 2.31% |  36.140 ms | 2.31% | 11.068G |     15x |  38.575 ms |
| I64 | xxhash_64 |  U32 |             8 |       UNIQUE | 400000000 |           64 |           0.99228 |  40.78% | 100.00% |    0.00% |     0.00% |    81.57% |      2x |     13x |  40.685 ms | 1.15% |  40.679 ms | 1.15% |  9.833G |     14x |  43.520 ms |
| I64 | xxhash_64 |  U32 |             8 |       UNIQUE | 400000000 |          128 |           0.85593 |  33.11% | 100.00% |    0.00% |     0.00% |    40.84% |      2x |     11x |  85.464 ms | 0.32% |  85.458 ms | 0.32% |  4.681G |     12x |  85.201 ms |
| I64 | xxhash_64 |  U32 |             8 |       UNIQUE | 400000000 |          256 |           0.47041 |  28.84% | 100.00% |    0.00% |     0.00% |    26.30% |      2x |     11x | 113.045 ms | 0.37% | 113.039 ms | 0.37% |  3.539G |     12x | 112.726 ms |
| I64 | xxhash_64 |  U32 |             8 |       UNIQUE | 400000000 |          512 |           0.15322 |  27.15% | 100.00% |    0.00% |     0.00% |    21.70% |      2x |     11x | 124.871 ms | 0.30% | 124.866 ms | 0.30% |  3.203G |     12x | 124.652 ms |
| I64 | xxhash_64 |  U32 |             8 |       UNIQUE | 400000000 |         1024 |          0.035256 |  26.45% | 100.00% |    0.00% |     0.00% |    20.33% |      2x |     11x | 130.669 ms | 0.24% | 130.664 ms | 0.24% |  3.061G |     12x | 130.467 ms |
| I64 | xxhash_64 |  U32 |             8 |       UNIQUE | 400000000 |         2048 |          0.012553 |  26.08% | 100.00% |    0.00% |     0.00% |    19.53% |      2x |     11x | 133.619 ms | 0.20% | 133.613 ms | 0.20% |  2.994G |     12x | 133.434 ms |
```

## arrow_bloom_filter_add_unique_size (arrow policy)
```
| Key |   Hash    | Word | WordsPerBlock | Distribution | NumInputs | FilterSizeMB | FalsePositiveRate | HBWPeak | LoadEff | StoreEff | L1HitRate | L2HitRate | Samples | Samples | CPU Time  | Noise | GPU Time  | Noise | Elem/s | Samples | Batch GPU |
|-----|-----------|------|---------------|--------------|-----------|--------------|-------------------|---------|---------|----------|-----------|-----------|---------|---------|-----------|-------|-----------|-------|--------|---------|-----------|
| I64 | xxhash_64 |  U32 |             8 |       UNIQUE | 400000000 |            1 |                 1 |  13.69% | 100.00% |    0.00% |    89.69% |    97.34% |      2x |     11x | 45.712 ms | 0.01% | 45.707 ms | 0.01% | 8.751G |     12x | 46.250 ms |
| I64 | xxhash_64 |  U32 |             8 |       UNIQUE | 400000000 |            2 |                 1 |  13.54% | 100.00% |    0.00% |    89.69% |    97.34% |      2x |     11x | 45.638 ms | 0.54% | 45.633 ms | 0.53% | 8.766G |     12x | 46.322 ms |
| I64 | xxhash_64 |  U32 |             8 |       UNIQUE | 400000000 |            4 |                 1 |  13.85% | 100.00% |    0.00% |    89.69% |    97.34% |      2x |     11x | 45.941 ms | 0.34% | 45.935 ms | 0.34% | 8.708G |     12x | 46.323 ms |
| I64 | xxhash_64 |  U32 |             8 |       UNIQUE | 400000000 |            8 |                 1 |  13.73% | 100.00% |    0.00% |    89.69% |    97.34% |      2x |     11x | 45.987 ms | 0.26% | 45.981 ms | 0.26% | 8.699G |     12x | 46.351 ms |
| I64 | xxhash_64 |  U32 |             8 |       UNIQUE | 400000000 |           16 |                 1 |  13.75% | 100.00% |    0.00% |    89.69% |    97.33% |      2x |     11x | 46.037 ms | 0.17% | 46.032 ms | 0.17% | 8.690G |     12x | 46.457 ms |
| I64 | xxhash_64 |  U32 |             8 |       UNIQUE | 400000000 |           32 |           0.99994 |  15.38% | 100.00% |    0.00% |    89.69% |    97.32% |      2x |     11x | 46.068 ms | 0.01% | 46.062 ms | 0.01% | 8.684G |     12x | 46.749 ms |
| I64 | xxhash_64 |  U32 |             8 |       UNIQUE | 400000000 |           64 |            0.9796 |  35.78% | 100.00% |    0.00% |    89.54% |    97.08% |      2x |     11x | 47.491 ms | 0.61% | 47.486 ms | 0.61% | 8.424G |     12x | 50.698 ms |
| I64 | xxhash_64 |  U32 |             8 |       UNIQUE | 400000000 |          128 |           0.66415 |  32.11% | 100.00% |    0.00% |    89.34% |    90.11% |      2x |     11x | 90.632 ms | 0.31% | 90.626 ms | 0.31% | 4.414G |     12x | 90.490 ms |
```

**Comment by mhaseeb123** [comment]
## Benchmark Results (Contains Unique Size)

## Hardware

```
GPU: NVIDIA RTX 5880 Ada Generation
SM Version: 890 (PTX Version: 860)
Number of SMs: 110
SM Default Clock Rate: 18446744071874 MHz
Global Memory: 23879 MiB Free / 48632 MiB Total
Global Memory Bus Peak: 960 GB/sec (384-bit DDR @10001MHz)
Max Shared Memory: 100 KiB/SM, 48 KiB/Block
L2 Cache Size: 98304 KiB
Maximum Active Blocks: 24/SM
Maximum Active Threads: 1536/SM, 1024/Block
Available Registers: 65536/SM, 65536/Block
ECC Enabled: No
```

## bloom_filter_contains_unique_size (default policy)
```
| Key |   Hash    | Word | WordsPerBlock | Distribution | NumInputs | FilterSizeMB | FalsePositiveRate | HBWPeak | LoadEff | StoreEff | L1HitRate | L2HitRate | Samples | Samples | CPU Time  | Noise  | GPU Time  | Noise  | Elem/s  | Samples | Batch GPU |
|-----|-----------|------|---------------|--------------|-----------|--------------|-------------------|---------|---------|----------|-----------|-----------|---------|---------|-----------|--------|-----------|--------|---------|---------|-----------|
| I64 | xxhash_64 |  U32 |             8 |       UNIQUE | 400000000 |            1 |                 1 |  71.29% |  55.56% |  100.00% |    45.55% |    80.58% |      2x |     56x |  9.108 ms | 17.05% |  9.103 ms | 17.05% | 43.944G |     57x | 10.090 ms |
| I64 | xxhash_64 |  U32 |             8 |       UNIQUE | 400000000 |            2 |                 1 |  70.57% |  55.56% |  100.00% |    45.01% |    80.77% |      2x |     53x |  9.505 ms | 12.60% |  9.500 ms | 12.60% | 42.105G |     54x | 10.185 ms |
| I64 | xxhash_64 |  U32 |             8 |       UNIQUE | 400000000 |            4 |                 1 |  69.93% |  55.56% |  100.00% |    44.74% |    80.85% |      2x |     52x |  9.646 ms | 11.21% |  9.641 ms | 11.21% | 41.492G |     53x | 10.510 ms |
| I64 | xxhash_64 |  U32 |             8 |       UNIQUE | 400000000 |            8 |                 1 |  70.15% |  55.56% |  100.00% |    44.61% |    80.87% |      2x |     52x |  9.719 ms | 11.26% |  9.714 ms | 11.26% | 41.176G |     53x | 10.512 ms |
| I64 | xxhash_64 |  U32 |             8 |       UNIQUE | 400000000 |           16 |                 1 |  70.00% |  55.56% |  100.00% |    44.55% |    80.84% |      2x |     52x |  9.742 ms | 10.73% |  9.737 ms | 10.73% | 41.081G |     53x | 10.556 ms |
| I64 | xxhash_64 |  U32 |             8 |       UNIQUE | 400000000 |           32 |           0.99997 |  62.85% |  55.56% |  100.00% |    43.98% |    80.98% |      2x |     50x | 10.179 ms | 10.62% | 10.174 ms | 10.62% | 39.318G |     51x | 10.989 ms |
| I64 | xxhash_64 |  U32 |             8 |       UNIQUE | 400000000 |           64 |           0.99228 |  40.63% |  55.56% |  100.00% |    42.95% |    80.97% |      2x |     43x | 11.877 ms |  0.55% | 11.872 ms |  0.55% | 33.694G |     44x | 12.029 ms |
| I64 | xxhash_64 |  U32 |             8 |       UNIQUE | 400000000 |          128 |           0.85593 |  33.79% |  55.56% |  100.00% |    43.42% |    29.93% |      2x |     13x | 39.508 ms |  0.02% | 39.503 ms |  0.01% | 10.126G |     14x | 39.363 ms |
| I64 | xxhash_64 |  U32 |             8 |       UNIQUE | 400000000 |          256 |           0.47041 |  30.81% |  55.56% |  100.00% |    43.31% |    13.18% |      2x |     11x | 53.381 ms |  0.01% | 53.375 ms |  0.00% |  7.494G |     12x | 53.283 ms |
| I64 | xxhash_64 |  U32 |             8 |       UNIQUE | 400000000 |          512 |           0.15322 |  29.98% |  55.56% |  100.00% |    43.31% |     8.14% |      2x |     11x | 57.949 ms |  0.01% | 57.943 ms |  0.01% |  6.903G |     12x | 57.858 ms |
| I64 | xxhash_64 |  U32 |             8 |       UNIQUE | 400000000 |         1024 |          0.035256 |  29.63% |  55.56% |  100.00% |    43.32% |     6.10% |      2x |     11x | 59.883 ms |  0.01% | 59.877 ms |  0.01% |  6.680G |     12x | 59.798 ms |
| I64 | xxhash_64 |  U32 |             8 |       UNIQUE | 400000000 |         2048 |          0.012553 |  29.47% |  55.56% |  100.00% |    43.26% |     5.26% |      2x |     11x | 60.790 ms |  0.01% | 60.784 ms |  0.01% |  6.581G |     12x | 60.708 ms |
```

## arrow_bloom_filter_contains_unique_size (arrow policy)
```
| Key |   Hash    | Word | WordsPerBlock | Distribution | NumInputs | FilterSizeMB | FalsePositiveRate | HBWPeak | LoadEff | StoreEff | L1HitRate | L2HitRate | Samples | Samples | CPU Time  | Noise | GPU Time  | Noise | Elem/s  | Samples | Batch GPU |
|-----|-----------|------|---------------|--------------|-----------|--------------|-------------------|---------|---------|----------|-----------|-----------|---------|---------|-----------|-------|-----------|-------|---------|---------|-----------|
| I64 | xxhash_64 |  U32 |             8 |       UNIQUE | 400000000 |            1 |                 1 |  50.20% |  55.56% |  100.00% |    12.14% |    87.61% |      2x |     59x |  8.522 ms | 1.53% |  8.517 ms | 1.53% | 46.964G |     61x |  8.526 ms |
| I64 | xxhash_64 |  U32 |             8 |       UNIQUE | 400000000 |            2 |                 1 |  53.59% |  55.56% |  100.00% |     9.66% |    88.15% |      2x |     57x |  8.855 ms | 0.70% |  8.850 ms | 0.70% | 45.197G |     59x |  8.801 ms |
| I64 | xxhash_64 |  U32 |             8 |       UNIQUE | 400000000 |            4 |                 1 |  53.25% |  55.56% |  100.00% |     8.39% |    88.30% |      2x |     56x |  8.955 ms | 1.38% |  8.950 ms | 1.38% | 44.694G |     58x |  8.945 ms |
| I64 | xxhash_64 |  U32 |             8 |       UNIQUE | 400000000 |            8 |                 1 |  52.40% |  55.56% |  100.00% |     7.75% |    88.37% |      2x |     56x |  9.048 ms | 1.32% |  9.043 ms | 1.32% | 44.231G |     58x |  9.015 ms |
| I64 | xxhash_64 |  U32 |             8 |       UNIQUE | 400000000 |           16 |                 1 |  52.49% |  55.56% |  100.00% |     7.43% |    88.38% |      2x |     55x |  9.097 ms | 1.28% |  9.092 ms | 1.28% | 43.994G |     57x |  9.069 ms |
| I64 | xxhash_64 |  U32 |             8 |       UNIQUE | 400000000 |           32 |           0.99994 |  34.80% |  55.56% |  100.00% |     6.52% |    88.57% |      2x |     50x | 10.123 ms | 1.23% | 10.119 ms | 1.22% | 39.531G |     51x | 10.182 ms |
| I64 | xxhash_64 |  U32 |             8 |       UNIQUE | 400000000 |           64 |            0.9796 |  26.24% |  55.56% |  100.00% |     6.24% |    88.36% |      2x |     27x | 18.728 ms | 2.77% | 18.723 ms | 2.77% | 21.364G |     29x | 17.842 ms |
| I64 | xxhash_64 |  U32 |             8 |       UNIQUE | 400000000 |          128 |           0.66415 |  33.71% |  55.56% |  100.00% |     2.28% |    59.51% |      2x |     13x | 39.464 ms | 0.02% | 39.458 ms | 0.01% | 10.137G |     14x | 39.322 ms |
```

File: examples/bloom_filter/host_bulk_example.cu
Comment (mhaseeb123) [reply examples/bloom_filter/host_bulk_example.cu:1]: I initially pushed a separate example for Arrow policy but the only difference between the two files was the 2 following lines where we create the filter with arrow filter policy type: 
```cpp
  // Arrow bloom filter policy type
  using arrow_filter_policy_type = cuco::arrow_filter_policy<key_type>;
  // bloom filter with arrow policy type
  using arrow_policy_filter_type = cuco::bloom_filter<key_type,
                                                      cuco::extent<size_t>,
                                                      cuda::thread_scope_device,
                                                      arrow_filter_policy_type>;
```
Hence, I thought it may be too redundant and just put everything in a function in the same file and just called it with the two types of filters in the main function. I am happy to revert to two examples if that's more preferred

Comment (mhaseeb123) [reply examples/bloom_filter/host_bulk_example.cu:1]: Done in 59f97911b31a1193c444789a44fd02b2730bbd0c (& 26ef2a8c3c766f78601e490783cadd2814b15610 readme updates). Can be reverted if needed.

**Comment by mhaseeb123** [comment]
> Can you please fix the doxygen check failures as well?

All done!

File: examples/bloom_filter/host_bulk_arrow_policy_example.cu [hunk 11]
```diff
@@ -0,0 +1,80 @@
...
+
+#include <cuco/bloom_filter.cuh>
+
+#include <thrust/count.h>
+#include <thrust/device_vector.h>
+#include <thrust/execution_policy.h>
+#include <thrust/sequence.h>
+
+#include <iostream>
+
```
Comment (PointKernel) [inline examples/bloom_filter/host_bulk_arrow_policy_example.cu]:
```suggestion

/**
 * @file arrow_policy_example.cu
 * @brief Demonstrates usage of an arrow-compatible bloom filter
 *
 * In addition to the default policy aimed at achieving the speed of light 
 * performance on the device, `cuCollections` offers an `arrow_filter_policy`
 * that allows users to easily create a bloom filter that mimics the behavior
 * of the bloom filter defined in Apache Arrow:
 * https://github.com/apache/arrow/blob/be1dcdb96b030639c0b56955c4c62f9d6b03f473/cpp/src/parquet/bloom_filter.cc#L219-L230.
 *
 * @note This example is for demonstration purposes only. It is not intended to show the most
 * performant way to do the example algorithm.
 */
 
```

Comment (PointKernel) [reply examples/bloom_filter/host_bulk_arrow_policy_example.cu]: To highlight our hassle-free usage of the arrow filter.  Let's also rename the file as `arrow_policy_example.cu`.

File: include/cuco/detail/bloom_filter/arrow_filter_policy.cuh [hunk 12]
```diff
@@ -0,0 +1,132 @@
...
+   * @param hash Hash value of the key
+   * @param word_index Target word/segment within the filter block
+   *
+   * @return The bit pattern for the word/segment in the filter block
+   */
+  __device__ constexpr word_type word_pattern(hash_result_type hash, std::uint32_t word_index) const
+  {
+    // Arrow's block-based bloom filter algorithm needs these eight odd SALT values to calculate
+    // eight indexes of bit to set, one bit in each 32-bit (uint32_t) word.
+    constexpr std::uint32_t SALT[bits_set_per_block] = {0x47b6137bU,
```
Comment (PointKernel) [inline include/cuco/detail/bloom_filter/arrow_filter_policy.cuh]: `SALT` should really be a static member of the policy class, e.g. 
```cuda
static constexpr cuda::std::array<std::uint32_t, 8> SALT{0x47b6137bU, ...};
```

File: examples/CMakeLists.txt [hunk 13]
```diff
@@ -47,3 +47,4 @@ ConfigureExample(STATIC_MULTIMAP_HOST_BULK_EXAMPLE "${CMAKE_CURRENT_SOURCE_DIR}/
 ConfigureExample(HYPERLOGLOG_HOST_BULK_EXAMPLE "${CMAKE_CURRENT_SOURCE_DIR}/hyperloglog/host_bulk_example.cu")
 ConfigureExample(HYPERLOGLOG_DEVICE_REF_EXAMPLE "${CMAKE_CURRENT_SOURCE_DIR}/hyperloglog/device_ref_example.cu")
 ConfigureExample(BLOOM_FILTER_HOST_BULK_EXAMPLE "${CMAKE_CURRENT_SOURCE_DIR}/bloom_filter/host_bulk_example.cu")
+ConfigureExample(BLOOM_FILTER_ARROW_POLICY_HOST_BULK_EXAMPLE "${CMAKE_CURRENT_SOURCE_DIR}/bloom_filter/host_bulk_arrow_policy_example.cu")
```
Comment (PointKernel) [inline examples/CMakeLists.txt]:
```suggestion
ConfigureExample(BLOOM_FILTER_ARROW_POLICY_EXAMPLE "${CMAKE_CURRENT_SOURCE_DIR}/bloom_filter/arrow_policy_example.cu")
```

File: include/cuco/detail/bloom_filter/arrow_filter_policy.cuh [hunk 14]
```diff
@@ -0,0 +1,132 @@
...
+ * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+ * See the License for the specific language governing permissions and
+ * limitations under the License.
+ */
+
+#pragma once
+
+#include <cuco/hash_functions.cuh>
+
+#include <cuda/std/__algorithm_>
```
Comment (PointKernel) [inline include/cuco/detail/bloom_filter/arrow_filter_policy.cuh]:
```suggestion
```
`cuda/std/__algorithm_` is still an internal experimental feature. Let's just use public headers for safety: `cuda::std::min/max` can be accessed from `<cuda/std/functional>` which is already included.

File: include/cuco/detail/bloom_filter/arrow_filter_policy.cuh [hunk 15]
```diff
@@ -0,0 +1,132 @@
...
+
+#include <cstdint>
+#include <nv/target>
+
+namespace cuco::detail {
+
+/**
+ * @brief A policy that defines how Arrow Block-Split Bloom Filter generates and stores a key's
+ * fingerprint.
+ *
```
Comment (PointKernel) [inline include/cuco/detail/bloom_filter/arrow_filter_policy.cuh:33]:
```suggestion
 *
 * Reference: https://github.com/apache/arrow/blob/be1dcdb96b030639c0b56955c4c62f9d6b03f473/cpp/src/parquet/bloom_filter.cc#L219-L230
 *
```

**Review by PointKernel — CHANGES_REQUESTED** [review]

File: include/cuco/detail/bloom_filter/arrow_filter_policy.cuh (hunk 14 above)
Comment (mhaseeb123) [reply include/cuco/detail/bloom_filter/arrow_filter_policy.cuh]: I actually tried that but I keep getting a compiler error: `/home/coder/cuCollections/include/cuco/detail/bloom_filter/arrow_filter_policy.cuh(111): error: namespace "cuda::std" has no member "min"`

Comment (PointKernel) [reply include/cuco/detail/bloom_filter/arrow_filter_policy.cuh]: Thank you for looking into this. Looks like the CCCL hasn't established a consistent accessibility solution for this utility yet.

File: README.md [hunk 16]
```diff
@@ -254,4 +254,7 @@ We plan to add many GPU-accelerated, concurrent data structures to `cuCollection
...
+
+#### Examples:
```
Comment (PointKernel) [inline README.md]:
```suggestion
```

**Review by PointKernel — APPROVED** [review]
Great work!

File: examples/bloom_filter/host_bulk_example.cu
Comment (sleeepyjack) [reply examples/bloom_filter/host_bulk_example.cu:1]: Sorry guys for being late to the party.IIUC the diff between `host_bulk_example` and the `arrow_policy_example` is only one line. If my understanding is correct, I'd say that there's not much new information conveyed to the user apart from how to pass a policy tparam to the filter type. Do we need this example at all?

File: examples/bloom_filter/host_bulk_example.cu [hunk 17]
```diff
@@ -25,15 +25,21 @@
...
 int main(void)
 {
-  // Generate 10'000 keys and insert the first 5'000 into the filter.
-  int constexpr num_keys = 10'000;
-  int constexpr num_tp   = num_keys * 0.5;
-  int constexpr num_tn   = num_keys - num_tp;
+  int constexpr num_keys    = 10'000;          ///< Generate 10'000 keys
+  int constexpr num_tp      = num_keys * 0.5;  ///< Insert the first half keys into the filter.
+  int constexpr num_tn      = num_keys - num_tp;
+  int constexpr sub_filters = 200;  ///< 200 sub-filters per bloom filter
```
Comment (sleeepyjack) [inline examples/bloom_filter/host_bulk_example.cu:31]: Wait, why did clang-format re-format all this stuff? Did we recently (between me adding this example a month ago and now) change the clang-format version or something? @PointKernel

Comment (PointKernel) [reply examples/bloom_filter/host_bulk_example.cu:31]: no, nothing changed.

Comment (PointKernel) [reply examples/bloom_filter/host_bulk_example.cu:31]: @mhaseeb123 are you using the pre-commit hook for code formatting? https://github.com/NVIDIA/cuCollections?tab=readme-ov-file#pre-commit-hook

Comment (mhaseeb123) [reply examples/bloom_filter/host_bulk_example.cu:31]: Yes, I am!

Comment (mhaseeb123) [reply examples/bloom_filter/host_bulk_example.cu:31]: I think clang-format did this as I added the `int constexpr sub_filters = 200` line which was a magic number before. Since it's declared with other variables, clang-format tries to add spaces such that the `=` is aligned for all variables in the list

Comment (sleeepyjack) [reply examples/bloom_filter/host_bulk_example.cu:31]: Whups, my bad, I missed that part.

**Comment by mhaseeb123** [comment]
Removed the new example and added a `@code` segment in `arrow_filter_policy.cuh` docstring to demo usage.

**Review by sleeepyjack — APPROVED** [review]
LGTM

Awesome work!
